[2022-08-28 23:53:15,290] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_and_populate_taxigov_datawarehouse.create_fact_daily_rides_table manual__2022-08-28T23:53:14.521136+00:00 [queued]>
[2022-08-28 23:53:15,295] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_and_populate_taxigov_datawarehouse.create_fact_daily_rides_table manual__2022-08-28T23:53:14.521136+00:00 [queued]>
[2022-08-28 23:53:15,295] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 23:53:15,295] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-28 23:53:15,296] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 23:53:15,305] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_fact_daily_rides_table> on 2022-08-28 23:53:14.521136+00:00
[2022-08-28 23:53:15,308] {standard_task_runner.py:52} INFO - Started process 4249 to run task
[2022-08-28 23:53:15,310] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'create_and_populate_taxigov_datawarehouse', 'create_fact_daily_rides_table', 'manual__2022-08-28T23:53:14.521136+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/create_and_populate_taxigov_datawarehouse_dag.py', '--cfg-path', '/tmp/tmpb9ytme6s', '--error-file', '/tmp/tmpqbdcmn57']
[2022-08-28 23:53:15,310] {standard_task_runner.py:80} INFO - Job 155: Subtask create_fact_daily_rides_table
[2022-08-28 23:53:15,352] {task_command.py:371} INFO - Running <TaskInstance: create_and_populate_taxigov_datawarehouse.create_fact_daily_rides_table manual__2022-08-28T23:53:14.521136+00:00 [running]> on host ddc8002727e0
[2022-08-28 23:53:15,401] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_and_populate_taxigov_datawarehouse
AIRFLOW_CTX_TASK_ID=create_fact_daily_rides_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-28T23:53:14.521136+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-28T23:53:14.521136+00:00
[2022-08-28 23:53:15,408] {base.py:68} INFO - Using connection ID 'redshift_default' for task execution.
[2022-08-28 23:53:16,767] {dbapi.py:231} INFO - Running statement: 
    DROP TABLE IF EXISTS fact_daily_rides;

    CREATE TABLE fact_daily_rides AS (
        SELECT
            DATE(started_at) AS date,
            COUNT(DISTINCT(dim_requests.id)) AS ride_requests_count,
            COUNT(DISTINCT(dim_rides.id)) AS rides_count,
            SUM(cost) AS total_rides_cost,
            SUM(cost)/COUNT(DISTINCT(rides_count)) AS average_cost_per_kilometer,
            AVG(
                DATEDIFF(
                    MINUTE,
                    started_at,
                    ended_at
                )
            ) AS average_ride_duration,
            AVG(
                DATEDIFF(
                    MINUTE,
                    requested_at,
                    approved_at
                )
            ) AS average_ride_request_sla,
            AVG(cost) AS average_ride_cost,
            AVG(distance) AS average_ride_distance
        FROM
            dim_rides
        LEFT JOIN 
            dim_requests ON dim_rides.request_id = dim_requests.id
        GROUP BY 
            date
    );, parameters: None
[2022-08-28 23:53:17,178] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InternalError_: aggregate function calls may not have nested aggregate or window function

[2022-08-28 23:53:17,195] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=create_and_populate_taxigov_datawarehouse, task_id=create_fact_daily_rides_table, execution_date=20220828T235314, start_date=20220828T235315, end_date=20220828T235317
[2022-08-28 23:53:17,203] {standard_task_runner.py:97} ERROR - Failed to execute job 155 for task create_fact_daily_rides_table (aggregate function calls may not have nested aggregate or window function
; 4249)
[2022-08-28 23:53:17,247] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-28 23:53:17,271] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
