[2022-08-25 11:17:48,252] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: taxi_rides_data.transfer_s3_to_redshift manual__2022-08-25T11:17:41.286617+00:00 [queued]>
[2022-08-25 11:17:48,262] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: taxi_rides_data.transfer_s3_to_redshift manual__2022-08-25T11:17:41.286617+00:00 [queued]>
[2022-08-25 11:17:48,262] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-25 11:17:48,262] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-25 11:17:48,262] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-25 11:17:48,282] {taskinstance.py:1397} INFO - Executing <Task(S3ToRedshiftOperator): transfer_s3_to_redshift> on 2022-08-25 11:17:41.286617+00:00
[2022-08-25 11:17:48,288] {standard_task_runner.py:52} INFO - Started process 7260 to run task
[2022-08-25 11:17:48,290] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'taxi_rides_data', 'transfer_s3_to_redshift', 'manual__2022-08-25T11:17:41.286617+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/taxi_rides_dag.py', '--cfg-path', '/tmp/tmpu848qgvb', '--error-file', '/tmp/tmpaqb3obol']
[2022-08-25 11:17:48,291] {standard_task_runner.py:80} INFO - Job 66: Subtask transfer_s3_to_redshift
[2022-08-25 11:17:48,353] {task_command.py:371} INFO - Running <TaskInstance: taxi_rides_data.transfer_s3_to_redshift manual__2022-08-25T11:17:41.286617+00:00 [running]> on host ddc8002727e0
[2022-08-25 11:17:48,434] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=taxi_rides_data
AIRFLOW_CTX_TASK_ID=transfer_s3_to_redshift
AIRFLOW_CTX_EXECUTION_DATE=2022-08-25T11:17:41.286617+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-25T11:17:41.286617+00:00
[2022-08-25 11:17:48,445] {base.py:68} INFO - Using connection ID 'redshift_default' for task execution.
[2022-08-25 11:17:48,451] {base.py:68} INFO - Using connection ID 'redshift_default' for task execution.
[2022-08-25 11:17:48,451] {base_aws.py:206} INFO - Credentials retrieved from login
[2022-08-25 11:17:48,467] {s3_to_redshift.py:167} INFO - Executing COPY command...
[2022-08-25 11:17:48,473] {base.py:68} INFO - Using connection ID 'redshift_default' for task execution.
[2022-08-25 11:17:50,191] {dbapi.py:231} INFO - Running statement: 
                    COPY PUBLIC.raw__taxigov_corridas 
                    FROM 's3://brazilian-politicians-taxi-rides/taxigov_corridas.csv'
                    credentials
                    'aws_access_key_id=awsuser;aws_secret_access_key=***'
                    csv;
        , parameters: None
[2022-08-25 11:17:51,106] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 168, in execute
    redshift_hook.run(sql, autocommit=self.autocommit)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/redshift_connector/cursor.py", line 240, in execute
    self._c.execute(self, operation, args)
  File "/home/airflow/.local/lib/python3.7/site-packages/redshift_connector/core.py", line 1783, in execute
    self.handle_messages(cursor)
  File "/home/airflow/.local/lib/python3.7/site-packages/redshift_connector/core.py", line 1969, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': 'XX000', 'M': 'S3ServiceException:The AWS Access Key Id you provided does not exist in our records.,Status 403,Error InvalidAccessKeyId,Rid NRF9WTBV8T83TM3Z,ExtRid 0qHAS7Bb7lDHUZxLfPtTbJxYnyci0u1nl3f/iZ3YEcEK29wqDCYXhX8Bw4fwZTnG2Cx4DGQW7vg=,CanRetry 1', 'D': '\n  -----------------------------------------------\n  error:  S3ServiceException:The AWS Access Key Id you provided does not exist in our records.,Status 403,Error InvalidAccessKeyId,Rid NRF9WTBV8T83TM3Z,ExtRid 0qHAS7Bb7lDHUZxLfPtTbJxYnyci0u1nl3f/iZ3YEcEK29wqDCYXhX8Bw4fwZTnG2Cx4DGQW7vg=,CanRetry 1\n  code:      8001\n  context:   Listing bucket=brazilian-politicians-taxi-rides prefix=taxigov_corridas.csv\n  query:     1470\n  location:  s3_utility.cpp:662\n  process:   padbmaster [pid=2992]\n  -----------------------------------------------\n', 'F': '../src/sys/xen_execute.cpp', 'L': '10520', 'R': 'pg_throw'}
[2022-08-25 11:17:51,120] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=taxi_rides_data, task_id=transfer_s3_to_redshift, execution_date=20220825T111741, start_date=20220825T111748, end_date=20220825T111751
[2022-08-25 11:17:51,132] {standard_task_runner.py:97} ERROR - Failed to execute job 66 for task transfer_s3_to_redshift ({'S': 'ERROR', 'C': 'XX000', 'M': 'S3ServiceException:The AWS Access Key Id you provided does not exist in our records.,Status 403,Error InvalidAccessKeyId,Rid NRF9WTBV8T83TM3Z,ExtRid 0qHAS7Bb7lDHUZxLfPtTbJxYnyci0u1nl3f/iZ3YEcEK29wqDCYXhX8Bw4fwZTnG2Cx4DGQW7vg=,CanRetry 1', 'D': '\n  -----------------------------------------------\n  error:  S3ServiceException:The AWS Access Key Id you provided does not exist in our records.,Status 403,Error InvalidAccessKeyId,Rid NRF9WTBV8T83TM3Z,ExtRid 0qHAS7Bb7lDHUZxLfPtTbJxYnyci0u1nl3f/iZ3YEcEK29wqDCYXhX8Bw4fwZTnG2Cx4DGQW7vg=,CanRetry 1\n  code:      8001\n  context:   Listing bucket=brazilian-politicians-taxi-rides prefix=taxigov_corridas.csv\n  query:     1470\n  location:  s3_utility.cpp:662\n  process:   padbmaster [pid=2992]\n  -----------------------------------------------\n', 'F': '../src/sys/xen_execute.cpp', 'L': '10520', 'R': 'pg_throw'}; 7260)
[2022-08-25 11:17:51,150] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-25 11:17:51,183] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
