[2022-08-25 11:41:02,466] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: taxi_rides_data.transfer_s3_to_redshift manual__2022-08-25T11:40:57.748304+00:00 [queued]>
[2022-08-25 11:41:02,475] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: taxi_rides_data.transfer_s3_to_redshift manual__2022-08-25T11:40:57.748304+00:00 [queued]>
[2022-08-25 11:41:02,476] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-25 11:41:02,476] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-25 11:41:02,476] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-25 11:41:02,495] {taskinstance.py:1397} INFO - Executing <Task(S3ToRedshiftOperator): transfer_s3_to_redshift> on 2022-08-25 11:40:57.748304+00:00
[2022-08-25 11:41:02,502] {standard_task_runner.py:52} INFO - Started process 8333 to run task
[2022-08-25 11:41:02,506] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'taxi_rides_data', 'transfer_s3_to_redshift', 'manual__2022-08-25T11:40:57.748304+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/taxi_rides_dag.py', '--cfg-path', '/tmp/tmp_021qkli', '--error-file', '/tmp/tmpb8djlaed']
[2022-08-25 11:41:02,507] {standard_task_runner.py:80} INFO - Job 72: Subtask transfer_s3_to_redshift
[2022-08-25 11:41:02,566] {task_command.py:371} INFO - Running <TaskInstance: taxi_rides_data.transfer_s3_to_redshift manual__2022-08-25T11:40:57.748304+00:00 [running]> on host ddc8002727e0
[2022-08-25 11:41:02,649] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=taxi_rides_data
AIRFLOW_CTX_TASK_ID=transfer_s3_to_redshift
AIRFLOW_CTX_EXECUTION_DATE=2022-08-25T11:40:57.748304+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-25T11:40:57.748304+00:00
[2022-08-25 11:41:02,658] {base.py:68} INFO - Using connection ID 'aws_credentials' for task execution.
[2022-08-25 11:41:02,663] {base.py:68} INFO - Using connection ID 'aws_credentials' for task execution.
[2022-08-25 11:41:02,663] {base_aws.py:206} INFO - Credentials retrieved from login
[2022-08-25 11:41:02,677] {s3_to_redshift.py:167} INFO - Executing COPY command...
[2022-08-25 11:41:02,683] {base.py:68} INFO - Using connection ID 'redshift_default' for task execution.
[2022-08-25 11:41:04,210] {dbapi.py:231} INFO - Running statement: 
                    COPY PUBLIC.raw__taxigov_corridas 
                    FROM 's3://brazilian-politicians-taxi-rides/taxigov_corridas.csv'
                    credentials
                    'aws_access_key_id=AKIAR2G6RXW7IQF76DLJ;aws_secret_access_key=***'
                    csv
			IGNOREHEADER 1
			MAXERROR 50;
        , parameters: None
[2022-08-25 11:41:05,527] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 168, in execute
    redshift_hook.run(sql, autocommit=self.autocommit)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/redshift_connector/cursor.py", line 240, in execute
    self._c.execute(self, operation, args)
  File "/home/airflow/.local/lib/python3.7/site-packages/redshift_connector/core.py", line 1783, in execute
    self.handle_messages(cursor)
  File "/home/airflow/.local/lib/python3.7/site-packages/redshift_connector/core.py", line 1969, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': 'XX000', 'M': "Load into table 'raw__taxigov_corridas' failed.  Check 'stl_load_errors' system table for details.", 'F': '../src/pg/src/backend/commands/commands_copy.c', 'L': '693', 'R': 'CheckMaxRowError'}
[2022-08-25 11:41:05,550] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=taxi_rides_data, task_id=transfer_s3_to_redshift, execution_date=20220825T114057, start_date=20220825T114102, end_date=20220825T114105
[2022-08-25 11:41:05,582] {standard_task_runner.py:97} ERROR - Failed to execute job 72 for task transfer_s3_to_redshift ({'S': 'ERROR', 'C': 'XX000', 'M': "Load into table 'raw__taxigov_corridas' failed.  Check 'stl_load_errors' system table for details.", 'F': '../src/pg/src/backend/commands/commands_copy.c', 'L': '693', 'R': 'CheckMaxRowError'}; 8333)
[2022-08-25 11:41:05,607] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-25 11:41:05,641] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
