[2022-08-28 23:30:37,844] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_and_populate_taxigov_datawarehouse.create_dim_requests_table manual__2022-08-28T23:30:33.098709+00:00 [queued]>
[2022-08-28 23:30:37,852] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_and_populate_taxigov_datawarehouse.create_dim_requests_table manual__2022-08-28T23:30:33.098709+00:00 [queued]>
[2022-08-28 23:30:37,852] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 23:30:37,852] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-28 23:30:37,852] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 23:30:37,863] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_dim_requests_table> on 2022-08-28 23:30:33.098709+00:00
[2022-08-28 23:30:37,866] {standard_task_runner.py:52} INFO - Started process 3070 to run task
[2022-08-28 23:30:37,868] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'create_and_populate_taxigov_datawarehouse', 'create_dim_requests_table', 'manual__2022-08-28T23:30:33.098709+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/create_and_populate_taxigov_datawarehouse_dag.py', '--cfg-path', '/tmp/tmptgoydyc7', '--error-file', '/tmp/tmpjf1647c0']
[2022-08-28 23:30:37,868] {standard_task_runner.py:80} INFO - Job 113: Subtask create_dim_requests_table
[2022-08-28 23:30:37,910] {task_command.py:371} INFO - Running <TaskInstance: create_and_populate_taxigov_datawarehouse.create_dim_requests_table manual__2022-08-28T23:30:33.098709+00:00 [running]> on host ddc8002727e0
[2022-08-28 23:30:37,970] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_and_populate_taxigov_datawarehouse
AIRFLOW_CTX_TASK_ID=create_dim_requests_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-28T23:30:33.098709+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-28T23:30:33.098709+00:00
[2022-08-28 23:30:37,977] {base.py:68} INFO - Using connection ID 'redshift_default' for task execution.
[2022-08-28 23:30:39,381] {dbapi.py:231} INFO - Running statement: 
    DROP TABLE IF EXISTS dim_requests;

    CREATE TABLE dim_requests AS ( 
        SELECT
            TO_HEX(
                SHA2(
                    CONCAT(
                        CAST(data_abertura AS STRING), 
                        nome_orgao
                    ),
                    256
                )
            ) AS id,
            UPPER(nome_orgao) AS requested_by,
            data_abertura AS requested_at,
            data_despacho AS approved_at,
            UPPER(motivo_corrida) AS reason,
            destino_solicitado_latitude AS requested_dropoff_latitude,
            destino_solicitado_longitude AS requested_dropoff_longitude,
            conteste_info AS commentary
        FROM
            raw__taxigov_corridas
    );, parameters: None
[2022-08-28 23:30:39,770] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedObject: type "string" does not exist

[2022-08-28 23:30:39,776] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=create_and_populate_taxigov_datawarehouse, task_id=create_dim_requests_table, execution_date=20220828T233033, start_date=20220828T233037, end_date=20220828T233039
[2022-08-28 23:30:39,783] {standard_task_runner.py:97} ERROR - Failed to execute job 113 for task create_dim_requests_table (type "string" does not exist
; 3070)
[2022-08-28 23:30:39,803] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-28 23:30:39,827] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
