[2022-08-27 15:25:54,797] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: taxi_rides_data.create_taxigov_raw_table scheduled__2022-08-26T10:32:38.642192+00:00 [queued]>
[2022-08-27 15:25:54,802] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: taxi_rides_data.create_taxigov_raw_table scheduled__2022-08-26T10:32:38.642192+00:00 [queued]>
[2022-08-27 15:25:54,802] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-27 15:25:54,802] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-27 15:25:54,802] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-27 15:25:54,811] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_taxigov_raw_table> on 2022-08-26 10:32:38.642192+00:00
[2022-08-27 15:25:54,816] {standard_task_runner.py:52} INFO - Started process 70 to run task
[2022-08-27 15:25:54,817] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'taxi_rides_data', 'create_taxigov_raw_table', 'scheduled__2022-08-26T10:32:38.642192+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/taxi_rides_dag.py', '--cfg-path', '/tmp/tmpcrjnf10v', '--error-file', '/tmp/tmpzn0zlo0u']
[2022-08-27 15:25:54,817] {standard_task_runner.py:80} INFO - Job 82: Subtask create_taxigov_raw_table
[2022-08-27 15:25:54,857] {task_command.py:371} INFO - Running <TaskInstance: taxi_rides_data.create_taxigov_raw_table scheduled__2022-08-26T10:32:38.642192+00:00 [running]> on host ddc8002727e0
[2022-08-27 15:25:54,907] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=taxi_rides_data
AIRFLOW_CTX_TASK_ID=create_taxigov_raw_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-26T10:32:38.642192+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-26T10:32:38.642192+00:00
[2022-08-27 15:25:54,914] {base.py:68} INFO - Using connection ID 'redshift_default' for task execution.
[2022-08-27 15:25:54,982] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 204, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 113, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "redshift-cluster-1.cezf1wahokbi.us-east-1.redshift.amazonaws.com" to address: Name or service not known

[2022-08-27 15:25:54,989] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=taxi_rides_data, task_id=create_taxigov_raw_table, execution_date=20220826T103238, start_date=20220827T152554, end_date=20220827T152554
[2022-08-27 15:25:55,008] {standard_task_runner.py:97} ERROR - Failed to execute job 82 for task create_taxigov_raw_table (could not translate host name "redshift-cluster-1.cezf1wahokbi.us-east-1.redshift.amazonaws.com" to address: Name or service not known
; 70)
[2022-08-27 15:25:55,029] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-27 15:25:55,059] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
